# Generated by Django 5.2.17 on 2026-09-08 10:51

import apps.accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='telefon')),
                ('first_name', models.CharField(max_length=100, verbose_name='ismi')),
                ('last_name', models.CharField(max_length=100, verbose_name='familiyasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('is_staff', models.BooleanField(default=False, verbose_name='xodim (admin panelga kiradi)')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name="ro'yxatdan o'tgan vaqti")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan vaqti")),
                ('role', models.CharField(choices=[('OWNER', 'Egasi'), ('ADMIN', 'Administrator'), ('TEACHER', "O'qituvchi"), ('ACCOUNTANT', 'Hisobchi')], max_length=20, verbose_name='roli')),
                ('status', models.CharField(choices=[('ACTIVE', 'Faol'), ('INACTIVE', 'Faol emas')], default='ACTIVE', max_length=20, verbose_name='holati')),
                ('started_at', models.DateField(verbose_name='boshlangan sana')),
                ('branches', models.ManyToManyField(blank=True, help_text="Bo'sh qoldirilsa - barcha filiallar.", related_name='memberships', to='centers.branch', verbose_name='filiallar')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='centers.center', verbose_name='markaz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': "Xodim (a'zolik)",
                'verbose_name_plural': "Xodimlar (a'zoliklar)",
                'ordering': ['-created_at'],
                'unique_together': {('user', 'center', 'role')},
            },
        ),
    ]
