# Generated by Django 5.2.17 on 2026-09-08 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan vaqti")),
                ('first_name', models.CharField(max_length=100, verbose_name='ismi')),
                ('last_name', models.CharField(max_length=100, verbose_name='familiyasi')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefon')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="tug'ilgan sana")),
                ('parent_name', models.CharField(blank=True, max_length=200, verbose_name='ota-ona ismi')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='ota-ona telefoni')),
                ('status', models.CharField(choices=[('ACTIVE', 'Faol'), ('ARCHIVED', 'Arxivlangan')], default='ACTIVE', max_length=20, verbose_name='holati')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='centers.center', verbose_name='markaz')),
            ],
            options={
                'verbose_name': "O'quvchi",
                'verbose_name_plural': "O'quvchilar",
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
