# Generated by Django 5.2.17 on 2026-09-08 10:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan vaqti")),
                ('name', models.CharField(max_length=200, verbose_name='nomi')),
                ('slug', models.SlugField(help_text='Kelajakda subdomen uchun ishlatiladi.', unique=True, verbose_name='qisqa nom')),
                ('status', models.CharField(choices=[('ACTIVE', 'Faol'), ('SUSPENDED', "To'xtatilgan")], default='ACTIVE', max_length=20, verbose_name='holati')),
            ],
            options={
                'verbose_name': 'Markaz',
                'verbose_name_plural': 'Markazlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan vaqti")),
                ('name', models.CharField(max_length=200, verbose_name='nomi')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='manzili')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefon')),
                ('status', models.CharField(choices=[('ACTIVE', 'Faol'), ('CLOSED', 'Yopilgan')], default='ACTIVE', max_length=20, verbose_name='holati')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='centers.center', verbose_name='markaz')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
                'ordering': ['name'],
                'unique_together': {('center', 'name')},
            },
        ),
    ]
