# Generated by Django 5.2.17 on 2026-09-08 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan vaqti")),
                ('name', models.CharField(max_length=200, verbose_name='nomi')),
                ('duration_months', models.PositiveSmallIntegerField(verbose_name='davomiyligi (oy)')),
                ('lessons_per_week', models.PositiveSmallIntegerField(verbose_name='haftasiga darslar soni')),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='asosiy narxi (oyiga)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Faol'), ('ARCHIVED', 'Arxivlangan')], default='ACTIVE', max_length=20, verbose_name='holati')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='centers.center', verbose_name='markaz')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['name'],
                'unique_together': {('center', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan vaqti")),
                ('date', models.DateField(verbose_name='sana')),
                ('name', models.CharField(max_length=200, verbose_name='nomi')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='centers.center', verbose_name='markaz')),
            ],
            options={
                'verbose_name': 'Bayram kuni',
                'verbose_name_plural': 'Bayram kunlari',
                'ordering': ['date'],
                'unique_together': {('center', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan vaqti")),
                ('name', models.CharField(max_length=100, verbose_name='nomi')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name="sig'imi")),
                ('status', models.CharField(choices=[('ACTIVE', 'Faol'), ('CLOSED', 'Yopilgan')], default='ACTIVE', max_length=20, verbose_name='holati')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='centers.branch', verbose_name='filial')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='centers.center', verbose_name='markaz')),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
                'ordering': ['branch__name', 'name'],
                'unique_together': {('branch', 'name')},
            },
        ),
    ]
