# Generated by Django 5.2.17 on 2026-09-08 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vaqti')),
                ('action', models.CharField(choices=[('CREATE', 'Yaratildi'), ('UPDATE', "O'zgartirildi"), ('DELETE', "O'chirildi")], max_length=10, verbose_name='amal')),
                ('object_type', models.CharField(max_length=100, verbose_name='obyekt turi')),
                ('object_id', models.CharField(max_length=64, verbose_name='obyekt ID')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='eski qiymatlar')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='yangi qiymatlar')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='centers.center', verbose_name='markaz')),
                ('user', models.ForeignKey(blank=True, help_text="Bo'sh bo'lsa - tizim amali.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Audit yozuvi',
                'verbose_name_plural': 'Audit jurnali',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['center', 'created_at'], name='audit_center_created_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_object_idx')],
            },
        ),
    ]
