# Generated by Django 5.2.17 on 2026-09-08 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan vaqti")),
                ('date', models.DateField(verbose_name='sana')),
                ('start_time', models.TimeField(verbose_name='boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='tugash vaqti')),
                ('status', models.CharField(choices=[('PLANNED', 'Rejalashtirilgan'), ('HELD', "O'tkazilgan"), ('CANCELLED', 'Bekor qilingan'), ('MOVED', "Ko'chirilgan")], default='PLANNED', max_length=20, verbose_name='holati')),
                ('topic', models.CharField(blank=True, max_length=300, verbose_name='mavzu')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan vaqti")),
                ('status', models.CharField(choices=[('PRESENT', 'Keldi'), ('ABSENT', 'Kelmadi'), ('LATE', 'Kechikdi'), ('EXCUSED', 'Sababli')], max_length=20, verbose_name='holati')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='izoh')),
                ('marked_at', models.DateTimeField(auto_now=True, verbose_name='belgilangan vaqti')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='centers.center', verbose_name='markaz')),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marked_attendances', to='accounts.membership', verbose_name='kim belgiladi')),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomat',
                'ordering': ['student__last_name', 'student__first_name'],
            },
        ),
    ]
