# Generated by Django 5.2.17 on 2026-09-08 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        ('lessons', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='students.student', verbose_name="o'quvchi"),
        ),
        migrations.AddField(
            model_name='lesson',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='centers.center', verbose_name='markaz'),
        ),
    ]
