# Generated by Django 5.2.17 on 2026-09-08 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
        ('lessons', '0002_initial'),
        ('study_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='study_groups.group', verbose_name='guruh'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='moved_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moved_from', to='lessons.lesson', verbose_name="ko'chirilgan dars"),
        ),
        migrations.AddField(
            model_name='lesson',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='courses.room', verbose_name='xona'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(help_text="Guruh o'qituvchisidan farq qilishi mumkin (o'rinbosar).", on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='accounts.membership', verbose_name="o'qituvchi"),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='lessons.lesson', verbose_name='dars'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['center', 'date'], name='lesson_center_date_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['group', 'date'], name='lesson_group_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('group', 'date', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('lesson', 'student')},
        ),
    ]
