# Generated by Django 5.2.17 on 2026-09-08 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('centers', '0001_initial'),
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan vaqti")),
                ('name', models.CharField(max_length=100, verbose_name='nomi')),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, help_text="Bo'sh qoldirilsa kursning asosiy narxidan olinadi.", max_digits=14, verbose_name='oylik narxi')),
                ('start_date', models.DateField(verbose_name='boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, help_text="Bo'sh qoldirilsa kurs davomiyligidan hisoblanadi.", null=True, verbose_name='tugash sanasi')),
                ('max_students', models.PositiveSmallIntegerField(default=15, verbose_name="maksimal o'quvchilar soni")),
                ('status', models.CharField(choices=[('PLANNED', 'Rejalashtirilgan'), ('ACTIVE', 'Faol'), ('FINISHED', 'Tugagan'), ('CANCELLED', 'Bekor qilingan')], default='PLANNED', max_length=20, verbose_name='holati')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='centers.branch', verbose_name='filial')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='centers.center', verbose_name='markaz')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='courses.course', verbose_name='kurs')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_groups', to='accounts.membership', verbose_name="o'qituvchi")),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'ordering': ['name'],
                'unique_together': {('center', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GroupSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan vaqti")),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')], verbose_name='hafta kuni')),
                ('start_time', models.TimeField(verbose_name='boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='tugash vaqti')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='centers.center', verbose_name='markaz')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='study_groups.group', verbose_name='guruh')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='courses.room', verbose_name='xona')),
            ],
            options={
                'verbose_name': 'Guruh jadvali',
                'verbose_name_plural': 'Guruh jadvallari',
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('group', 'weekday', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartirilgan vaqti")),
                ('joined_at', models.DateField(verbose_name="qo'shilgan sana")),
                ('left_at', models.DateField(blank=True, null=True, verbose_name='chiqqan sana')),
                ('status', models.CharField(choices=[('ACTIVE', 'Faol'), ('LEFT', 'Chiqib ketgan'), ('TRANSFERRED', "Boshqa guruhga o'tgan")], default='ACTIVE', max_length=20, verbose_name='holati')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='centers.center', verbose_name='markaz')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='study_groups.group', verbose_name='guruh')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.student', verbose_name="o'quvchi")),
            ],
            options={
                'verbose_name': "Guruhdagi o'quvchi",
                'verbose_name_plural': "Guruhdagi o'quvchilar",
                'ordering': ['-joined_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('group', 'student'), name='unique_active_enrollment_per_group')],
            },
        ),
    ]
